import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import './../globals.css'

// Main navigation page for authenticated users.
export default async function ProtectedPage() {
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name) { return cookieStore.get(name)?.value },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    redirect('/')
  }

  return (
    <div style={{
      padding: '40px',
      fontFamily: 'monospace',
      backgroundColor: '#f2eee5',
      minHeight: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: '20px' // Shifted up by reducing padding-top
    }}>

      <div style={{
        position: 'absolute',
        top: '20px',
        right: '20px',
        backgroundColor: '#fff',
        padding: '10px 20px',
        border: '2px solid #000'
      }}>
        <span>Logged in as: <strong>{user.email}</strong></span>
      </div>

      <h1 style={{ fontFamily: 'sans-serif', marginBottom: '20px', fontWeight: 'bold', fontSize: '2em' }}>Welcome</h1>

      <p style={{ textAlign: 'center', maxWidth: '800px', marginBottom: '40px', fontSize: '1.1em', lineHeight: '1.6' }}>
        At The Humor Project, we use LLMs to create funny captions for images uploaded by the user. You can interact with this app in two ways: <br /><br />
        <span style={{ fontSize: '1.2em', display: 'block' }}><b>Rate</b> how funny you find the captions previously generated by the model</span>
        <span style={{ fontSize: '1.2em', display: 'block' }}><b>Generate</b> captions of your own by uploading an image to the model</span>
      </p>

      <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
        <Link href="/protected/rate" className="rate-button" style={{
          padding: '20px 40px',
          fontSize: '1.2rem',
          color: '#fff',
          backgroundColor: '#0070f3',
          border: '2px solid #000',
          boxShadow: '4px 4px 0px #000',
          textDecoration: 'none',
          textAlign: 'center',
          transition: 'transform 0.2s, background-color 0.2s',
        }}>
          Rate Captions
        </Link>

        <Link href="/protected/generate" className="generate-button" style={{
          padding: '20px 40px',
          fontSize: '1.2rem',
          color: '#fff',
          backgroundColor: '#4CAF50',
          border: '2px solid #000',
          boxShadow: '4px 4px 0px #000',
          textDecoration: 'none',
          textAlign: 'center',
          transition: 'transform 0.2s, background-color 0.2s',
        }}>
          Generate Captions
        </Link>
      </div>
    </div>
  )
}
